Models/SupportController.cs
using Microsoft.AspNetCore.Mvc;

namespace MEDManager.Models
{
    public class SupportController : Controller
    {
        // GET: SupportController
        public ActionResult Index()
        {
            return View("Index");
        }

    }
}

Controllers/DashboardController.cs
using MEDManager.Data;
using MEDManager.Models;
using MEDManager.ViewModel;
using MEDManager.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;


namespace MEDManager.Controllers
{
    [Authorize]
    public class DashboardController : Controller
    {
        private readonly ApplicationDbContext _dbContext;
        private readonly UserManager<Doctor> _userManager;

        private string? _doctorId => _userManager.GetUserId(User);

        public DashboardController(ApplicationDbContext dbContext, UserManager<Doctor> userManager)
        {
            _userManager = userManager;
            _dbContext = dbContext;
        }
        // GET: DashboardController
        public ActionResult Index()
        {
            MostMedicamentInPrescriptionStat();
            MostConsultedPatientsStat();
            MostMedicalHistoryInPatientStat();
            PatientsByAgeStat();
            MedicamentsCountStat();
            return View();
        }

        private void MostConsultedPatientsStat()
        {
            var mostConsultedPatients = _dbContext.Patients
                .Include(p => p.Prescriptions)
                .Where(p => p.DoctorId == _doctorId)
                .OrderByDescending(p => p.Prescriptions.Count).Take(5).ToList();

            var patientLabels = new List<string>();
            var patientData = new List<int>();

            foreach (var patient in mostConsultedPatients)
            {
                patientLabels.Add(patient.FirstName + " " + patient.LastName);
                patientData.Add(patient.Prescriptions.Count);
            }

            ViewBag.PatientLabels = patientLabels;
            ViewBag.PatientData = patientData;
        }

        private void MostMedicamentInPrescriptionStat()
        {
            var mostMedicamentInPrescription = _dbContext.Medicaments
                .Include(p => p.Prescriptions)
                .OrderByDescending(p => p.Prescriptions.Count).Take(5).ToList();

            var medicamentLabels = new List<string>();
            var medicamentData = new List<int>();

            foreach (var medicament in mostMedicamentInPrescription)
            {
                medicamentLabels.Add(medicament.Name);
                medicamentData.Add(medicament.Prescriptions.Count);
            }

            ViewBag.MedicamentLabels = medicamentLabels;
            ViewBag.MedicamentData = medicamentData;
        }

        private void MostMedicalHistoryInPatientStat()
        {
            var mostMedicalHistoryInPatientStat = _dbContext.MedicalHistories
                .Include(p => p.Patients)
                .OrderByDescending(p => p.Patients.Count).Take(5).ToList();

            var medicalHistoryLabels = new List<string>();
            var medicalHistoryData = new List<int>();

            foreach (var medicalHistory in mostMedicalHistoryInPatientStat)
            {
                medicalHistoryLabels.Add(medicalHistory.Name);
                medicalHistoryData.Add(medicalHistory.Patients.Count);
            }

            ViewBag.MedicalHistoryLabels = medicalHistoryLabels;
            ViewBag.MedicalHistoryData = medicalHistoryData;
        }

        private void PatientsByAgeStat()
        {
            var patientByAge = _dbContext.Patients.Where(p => p.DoctorId == _doctorId)
                .GroupBy(p => p.Age)
                .Select(g => new
                {
                    Age = g.Key,
                    Count = g.Count()
                }).ToList();

            var patientByAgeLabels = new List<string>();
            var patientByAgeData = new List<int>();

            for (int i = 0; i < 5; i++)
            {
                var min = i * 20;
                var max = (i + 1) * 20;

                var label = $"{min}-{max} ans";
                var count = patientByAge.Where(p => p.Age >= min && p.Age < max).Sum(p => p.Count);

                patientByAgeLabels.Add(label);
                patientByAgeData.Add(count);
            }

            ViewBag.PatientByAgeLabels = patientByAgeLabels;
            ViewBag.PatientByAgeData = patientByAgeData;
        }
        private void MedicamentsCountStat()
        {
            var medicamentsCountStat = _dbContext.Medicaments
                .ToList();

            var medicamentCountLabels = new List<string>();
            var medicamentCountData = new List<int>();


            medicamentCountLabels.Add("nombre de médicaments");
            medicamentCountData.Add(medicamentsCountStat.Count());

            ViewBag.MedicamentCountLabels = medicamentCountLabels;
            ViewBag.MedicamentCountData = medicamentCountData;
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-icons/1.8.1/font/bootstrap-icons.min.css"
        rel="stylesheet">
    <link href="~/css/bootstrap-multiselect.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" />

    <script src="https://davidstutz.github.io/bootstrap-multiselect/docs/js/jquery-2.2.4.min.js"></script>
    <script src="https://davidstutz.github.io/bootstrap-multiselect/docs/js/bootstrap.bundle-4.5.2.min.js"></script>
    <script src="https://davidstutz.github.io/bootstrap-multiselect/dist/js/bootstrap-multiselect.js"></script>

    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

    @RenderSection("Scripts", required: false)

    <style>
        body {
            display: flex;
            min-height: 100vh;
        }

        /* Style pour la sidebar */
        .sidebar {
            height: 100vh;
            background-color: #343a40;
            /* Couleur de fond de la sidebar */
            color: white;
            min-width: 250px;
        }

        .sidebar .nav-link {
            color: white;
        }

        .navbar-color {
            background-color: rgb(222, 226, 230, 0.5);
            backdrop-filter: blur(6px);
            border-bottom: 1px solid #495057;
        }

        .sidebar .nav-link:hover {
            background-color: #495057;
        }

        /* Style pour le contenu principal */
        .content {
            flex-grow: 1;
        @*
            padding:
            20px;
            *@
        }
    </style>
</head>

<body>
    <div class="sidebar d-flex flex-column p-3 sticky-top">
        <h2 class="text-center">Med Manager</h2>
        <hr />
        <ul class="nav nav-pills flex-column">
            @if (User?.Identity?.IsAuthenticated == true)
            {
                <li class="nav-item">
                    <a asp-action="Index" asp-controller="Dashboard" asp-route-id="" class="nav-link"
                        aria-current="page">Accueil</a>
                </li>
                <li class="nav-item">
                    <a asp-action="Index" asp-controller="Medicament" asp-route-id="" class="nav-link"
                        aria-current="page">Médicaments</a>
                </li>
                <li class="nav-item">
                    <a asp-action="Index" asp-controller="Patient" asp-route-id="" class="nav-link" aria-current="page">Patients</a>
                </li>
                <li class="nav-item">
                    <a asp-action="Index" asp-controller="Allergy" asp-route-id="" class="nav-link" aria-current="page">Allergies</a>
                </li>
                <li class="nav-item">
                    <a asp-action="Index" asp-controller="MedicalHistory" asp-route-id="" class="nav-link"
                        aria-current="page">Antécedents</a>
                </li>
                <li class="nav-item">
                    <a asp-action="Index" asp-controller="Prescription" asp-route-id="" class="nav-link"
                        aria-current="page">Ordonnances</a>
                </li>
            }
            else
            {

            }
            <li class="mt-auto">
                <a class="nav-link" asp-controller="Support" asp-action="Index">FAQ & Contact</a>
            </li>
        </ul>
    </div>

    <div class="content">
        <nav class="navbar navbar-expand-lg navbar-color px-4 sticky-top">
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ml-auto">
                    @if (User?.Identity?.IsAuthenticated == true)
                    {
                            <li class="nav-item" class="navbar-text">
                                <a class="nav-link active bi bi-person-circle" asp-action="Edit" asp-controller="Account"> @User.Identity.Name</a>
                            </li>
                            <li class="nav-item">
                                <a asp-action="Logout" asp-controller="Account" asp-route-id="" class="nav-link"
                                    aria-current="page">Se déconnecter</a>
                            </li>
                    }
                    else
                    {
                            <li class="nav-item">
                                <a class="nav-link" href="@Url.Action("Login", "Account")">Se connecter</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="@Url.Action("Register", "Account")">S'inscrire</a>
                            </li>
                    }
                </ul>
            </div>
        </nav>

        <!-- Contenu principal de la page -->
        <div class="container mt-4">
            @RenderBody()
        </div>
    </div>

</body>

</html>